version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    container_name: api
    volumes:
      - ./.env:/opt/app/.env
#    привязка (монтирование) конкретного файла или каталога из хост-системы внутрь контейнера. озволяет сохранять данные даже после остановки и удаления контейнера. Таким образом, изменения, внесенные в .env на хост-системе, будут отражены в контейнере, и наоборот.
    networks:
      - myNetwork
# Определяем сеть. К примеру контейнеры будут в одной сети.
    depends_on:
      - rmq
  # Сначала будет поднят контейнер rmq  а только затем будет запущен api благодаря команде * depends_on *
  rmq:
    image: rabbitmq:3-management
    restart: always
    networks:
    - myNetwork
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  myNetwork:
    driver: bridge


#